mysite/blog/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('category/', CategoryListView.as_view(), name='category'),
    path('about/', AboutPageView.as_view(), name='about'),
    path('category/<slug:slug>/', CategoryPageView.as_view(), name='cat'),
    path('post/<slug:slug>/', PostPageView.as_view(), name='post'),
    # path('tag/<slug:slug>/', show_tags, name='tag'),
    path('tag/<slug:slug>/', PostByTagsListView.as_view(), name='tag'),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('edit_post/<slug:slug>/', PostEditPage.as_view(), name='edit_post'),
    path('delete_post/<slug:slug>/', PostDeletePage.as_view(), name='delete_post'),
]

mysite/comments/urls.py
from django.urls import path
from .views import *

app_name = 'comments'

urlpatterns = [
    path('add/<slug:slug>/', CommentCreateView.as_view(), name='add_comment'),
    path('list/<slug:slug>/', PostCommentsListView.as_view(), name='post_comments'),
    path('moderate/<int:pk>/', moderate_comment, name='moderate_comment'),
]

mysite/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from mysite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
    path('comments/', include('comments.urls')),
]


if settings.DEBUG:

    urlpatterns = [
        path("__debug__/", include("debug_toolbar.urls")),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class PostTags(models.Model):
    tag = models.CharField(max_length=100, db_index=True, verbose_name='Тег')
    slug = models.SlugField(max_length=150, db_index=True, unique=True)

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'

    def get_absolute_url(self):
        return reverse('tag', kwargs={'slug': self.slug})

    def __str__(self):
        return self.tag


class Category(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    slug = models.CharField(max_length=100, unique=True, verbose_name='URL')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан', null=True, blank=True)
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name="Фото", blank=True, null=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('cat', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

class Post(models.Model):
    class Status(models.IntegerChoices):
        published = 1, 'Опубликовано'
        draft = 0, 'Черновик'
    title = models.CharField(max_length=250, verbose_name='Наименование')
    slug = models.SlugField(unique=True, verbose_name='URL')
    content = models.TextField(verbose_name='Текст')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан', null=True, blank=True)
    updated = models.DateTimeField(auto_now=True, verbose_name='Изменён', null=True)
    is_published = models.BooleanField(choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)), default=Status.draft, verbose_name='Опубликовано')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts', verbose_name='Категория')
    tags = models.ManyToManyField(PostTags, related_name='tags', verbose_name='Теги', blank=True)
    image = models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name="Фото", blank=True, null=True)

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['-created']

    def active_comments(self):
        """Возвращает только активные комментарии"""
        return self.comments.filter(is_active=True)

    def active_comments_count(self):
        """Возвращает количество активных комментариев"""
        return self.comments.filter(is_active=True).count()

    def get_absolute_url(self):
        return reverse('post', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


class Gallery(models.Model):
    image = models.ImageField(upload_to='gallery/%Y/%m/%d', blank=True, null=True, verbose_name='Изображение')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='images')

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Галерея изображений'

mysite/blog/forms.py
from django import forms
from django.template.defaultfilters import title

from .models import Post


class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'tags': forms.CheckboxSelectMultiple(),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'is_published': forms.CheckboxInput(attrs={'class': 'checkbox'}),
        }

mysite/blog/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from .forms import AddPostForm
from .models import Category, Post, PostTags


# Create your views here.
class HomePageView(TemplateView):
    template_name = 'blog/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'Home Page'
        return context


class AboutPageView(LoginRequiredMixin,TemplateView):
    template_name = 'blog/about.html'
    login_url = '/users/login/'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.info(request, '🔐 Пожалуйста, авторизуйтесь для доступа к этой странице.')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = 'About Page'
        return context

class CategoryListView(ListView):
    # model = Category
    template_name = 'blog/category_list.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.none()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории'
        return context



class CategoryPageView(ListView):
    # model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    slug_url_kwarg = 'slug'
    allow_empty = False

    def get_queryset(self):
        return Post.objects.filter(category__slug=self.kwargs['slug'], is_published=True)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Category.objects.get(slug=self.kwargs['slug'])
        return context


class PostPageView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = Post.objects.get(slug=self.kwargs['slug'])
        return context


class PostByTagsListView(ListView):
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    paginate_by = 5
    allow_empty = False

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs['slug'], is_published=True)

    def get_context_data(self, **kwargs):
        contex = super().get_context_data(**kwargs)
        contex['title'] = PostTags.objects.get(slug=self.kwargs['slug'])
        return contex

def show_tags(request, slug):
    tags = PostTags.objects.all()
    tag = get_object_or_404(PostTags, slug=slug)
    posts = tag.tags.filter(is_published=True).prefetch_related('category')
    context = {
        'tag': tag,
        'posts': posts,
        'tags': tags,
        'title': tag.tag
    }
    return render(request, 'blog/home.html', context=context)


class AddPostView(LoginRequiredMixin, CreateView):
    # model = Post
    form_class = AddPostForm
    template_name = 'blog/add_post.html'
    # success_url = reverse_lazy('index')  # замени на свой URL

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.info(request, '🔐 Пожалуйста, авторизуйтесь для доступа к этой странице.')
        return super().dispatch(request, *args, **kwargs)


class PostEditPage(LoginRequiredMixin, UpdateView):
    model = Post
    fields = '__all__'
    template_name = 'blog/add_post.html'
    success_url = reverse_lazy('index')
    extra_context = {
        'title': 'Редактирование страницы'
    }

class PostDeletePage(LoginRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('index')

mysite/blog/templates/blog/about.html
{% extends 'base.html' %}


{% block content %}
<h1>{{ title }}</h1>
{% endblock %}

mysite/blog/templates/blog/add_post.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Сохранить</button>
    </form>
{% endblock %}

mysite/blog/templates/blog/category_list.html
{% extends 'base.html' %}
{% load blog_tags %}

{% block content %}
    {{ title }}
    <h1>Category List</h1>
    {% get_category as categories %}
    {% for category in categories %}
        <a href="{{ category.get_absolute_url }}">{{ category }}</a>
    {% endfor %}
{% endblock %}

mysite/blog/templates/blog/home.html
{% extends 'base.html' %}


{% block content %}
<h1>{{ title }}</h1>
    {% for post in posts %}
        <p><a href="{{ post.get_absolute_url }}">{{ post }}</a></p>
    {% endfor %}
{% endblock %}

mysite/blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    Удалить - {{ post }} ?
    <form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Удалить</button>
    </form>
{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends 'base.html' %}


{% block content %}
    <h1>{{ post }}</h1>
    <a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a>
    {% if post.image %}
            <p><img src="{{ post.image.url }}" alt=""></p>
        {% else %}
            <p><img src="/media/users/noimg.png" alt=""></p>
        {% endif %}
    <p>{{ post.content }}</p>
    {% with post.tags.all as tags %}
            {% if tags %}
                <div class="post_tag">
                    Теги:
                    {% for tag in tags %}
                        <a class="tag_link" href="{{ tag.get_absolute_url }}">{{ tag }}</a>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
    {% for image in post.images.all %}
        <img src="{{ image.image.url }}" alt="">
    {% endfor %}

    <div class="mt-4">
    <h3>Комментарии</h3>
    {% with comments_count=post.comments.count %}
    <p>Всего комментариев: {{ post.active_comments_count }}</p>
    {% endwith %}

    <!-- Последние 3 комментария -->
    {% for comment in post.active_comments|slice:":3" %}
    <div class="card mb-2">
        <div class="card-body">
            <h6>{{ comment.author.username }}</h6>
            <p>{{ comment.text|truncatewords:20 }}</p>
        </div>
    </div>
    {% endfor %}

    <a href="{% url 'comments:post_comments' post.slug %}" class="btn btn-outline-primary">
        Все комментарии
    </a>
    <a href="{% url 'comments:add_comment' post.slug %}" class="btn btn-primary">
        Добавить комментарий
    </a>
</div>
    <a href="{% url 'delete_post' post.slug %}">Удалить</a>
    <a href="{% url 'edit_post' post.slug %}">Редактировать</a>
{% endblock %}

mysite/blog/templates/blog/tags.html
{% if tags %}
    <h2>Tags</h2>
    <div class="tags">
        {% for tag in tags %}
            <p><a class="tag" href="{{ tag.get_absolute_url }}">{{ tag }}</a></p>
        {% endfor %}
    </div>
{% endif %}